//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Additional_ch_config
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Additional_ch_config()
        {
            this.customer_booking_addl_ch = new HashSet<customer_booking_addl_ch>();
        }
    
        public int additional_ch_id { get; set; }
        public string charges_title { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> policy_id { get; set; }
        public Nullable<int> vanue_id { get; set; }
    
        public virtual policy policy { get; set; }
        public virtual vanue vanue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_booking_addl_ch> customer_booking_addl_ch { get; set; }
    }
}
