//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank
    {
        public int bank_id { get; set; }
        public string bank_name { get; set; }
        public string Account_title { get; set; }
        public string Account_no { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
