//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public booking_type()
        {
            this.booking_schedule = new HashSet<booking_schedule>();
        }
    
        public int booking_type_id { get; set; }
        public string booking_type1 { get; set; }
        public Nullable<bool> booking_type_status { get; set; }
        public Nullable<int> vanue_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking_schedule> booking_schedule { get; set; }
        public virtual vanue vanue { get; set; }
    }
}
