//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_booking_addl_ch
    {
        public int cus_booking_addl_ch_id { get; set; }
        public Nullable<int> customer_booking_id { get; set; }
        public Nullable<int> additional_ch_id { get; set; }
        public Nullable<decimal> amount { get; set; }
    
        public virtual Additional_ch_config Additional_ch_config { get; set; }
        public virtual customer_booking customer_booking { get; set; }
    }
}
