//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class holiday
    {
        public int holiday_id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> holiday_date { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
