//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBooking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OB_entities : DbContext
    {
        public OB_entities()
            : base("name=OB_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Additional_ch_config> Additional_ch_config { get; set; }
        public virtual DbSet<bank> banks { get; set; }
        public virtual DbSet<booking_schedule> booking_schedule { get; set; }
        public virtual DbSet<booking_type> booking_type { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customer_booking> customer_booking { get; set; }
        public virtual DbSet<customer_booking_addl_ch> customer_booking_addl_ch { get; set; }
        public virtual DbSet<directorate> directorates { get; set; }
        public virtual DbSet<holiday> holidays { get; set; }
        public virtual DbSet<policy> policies { get; set; }
        public virtual DbSet<shift> shifts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<team_category> team_category { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<vanue> vanues { get; set; }
        public virtual DbSet<week_days> week_days { get; set; }
    }
}
