//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.customer_booking = new HashSet<customer_booking>();
        }
    
        public int user_id { get; set; }
        public int role_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<bool> record_status { get; set; }
        public Nullable<int> dte_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string email { get; set; }
        public string Emp_Name { get; set; }
        public string DHA_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_booking> customer_booking { get; set; }
        public virtual directorate directorate { get; set; }
        public virtual user_role user_role { get; set; }
    }
}
